blog/urls.py
from . import views
from django.urls import path


urlpatterns = [
    path('', views.HomeView.as_view(), name="home_view"),
    path('about', views.AboutView.as_view(), name="about_view"),
    path('<slug:slug>', views.BlogView.as_view(), name="blog_view"),
]

translation_app/urls.py
from . import views
from django.urls import path


urlpatterns = [
    path('', views.translator_view, name="translator_view"),
]

translator/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('translate/', include('translation_app.urls'))
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

STATUS = ((0, "Draft"), (1, "Publish"))
class Post(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()
    date_created = models.DateTimeField(auto_now_add = True)
    slug = models.SlugField(max_length=200, unique=True)
    author = models.ForeignKey(User, on_delete = models.CASCADE)  # Delete posts for user if user deleted
    status = models.IntegerField(choices=STATUS, default=0)

    def __str__(self):
        return f"{self.title} {self.author}"

translation_app/models.py
from django.db import models

# Create your models here.

blog/views.py
from django.shortcuts import render
from .models import Post
from django.views.generic import DetailView, TemplateView, ListView

# Create your views here.

class BlogView(DetailView):
    model = Post
    template_name = 'blog/blog.html'

class HomeView(ListView):
    template_name = 'blog/index.html'
    queryset = Post.objects.filter(status=1).order_by('-date_created')

class AboutView(TemplateView):
    template_name = 'blog/about.html'

translation_app/views.py
from django.shortcuts import render
from .translate import translate


# Create your views here.
def translator_view(request):
    if request.method == 'POST':
        user_inp_text = request.POST['my_textarea']
        output = translate(user_inp_text)
        return render(request, 'translation_app/translator.html', {'output_text': output, 'original_text': user_inp_text})
    
    else:
        return render(request, 'translation_app/translator.html')

blog/templates/blog/about.html
{% extends "blog/base.html" %}

{% block content %}
<h1>
    This is th ABOUT PAGE
</h1>
{% endblock content %}

blog/templates/blog/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} Document {% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light shadow mb-3" id=""mainNav>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="navbar-brand p-3" href="{% url 'home_view' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="navbar-brand p-3" href="{% url 'about_view' %}">About Us</a>
                </li>
                <li class="nav-item">
                    <a class="navbar-brand p-3" href="{% url 'translator_view' %}">Translator</a>
                </li>
            </ul>
        </div>
    </nav>
    {% block content %}{% endblock %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3"
        crossorigin="anonymous"></script>
</body>

</html>

blog/templates/blog/blog.html
{% extends 'blog/base.html' %}

{% block content %}
<h1>Template Loaded</h1>
<h3>{{object.title}}</h3>
<p>{{object.content}}</p>

{% endblock content %}

blog/templates/blog/index.html
{% extends 'blog/base.html' %}
{% block title %}Home Page{% endblock %}

{% block content %}
<h1>This is the home page</h1>
<div class="container">
    {% for obj in post_list %}
    <div class="card m-3">
        <div class="card-body">
            <h2 class="card-title">
                {{obj.title}}
            </h2>
            <p class="card-text">
                {{obj.content | slice:"400"}}
            </p>
            <p class="card-text">
                Author: {{obj.author | title}}
            </p>
            <a class="btn btn-primary" href="{% url 'blog_view' obj.slug %}">Read More</a>


        </div>
    </div>
    {% endfor %}
</div>
{% endblock content %}

translation_app/templates/translation_app/translator.html
{% extends 'blog/base.html' %}
{% block content %}
<div class="container">
    <form action="{% url 'translator_view' %}" method="post">
        {% csrf_token %}
        <div class="row">
            <div class="col-sm-6 mt-3 left">
                <textarea class="form-control" rows="3" name="my_textarea">{{original_text}}</textarea>
            </div>
            <div class="col-sm-6 mt-3 left">
                <textarea class="form-control" rows="3">{{output_text}}</textarea>
                <input class="btn btn-primary ml-3 mt-3" type="submit" value="Submit">
            </div>
        </div>
    </form>
</div>
{% endblock content %}